import {
  BoxGeometry,
  BufferGeometry,
  CatmullRomCurve3,
  Color,
  CylinderGeometry,
  DataTexture,
  DoubleSide,
  Float32BufferAttribute,
  Group,
  Matrix4,
  Mesh,
  MeshStandardMaterial,
  PlaneGeometry,
  Quaternion,
  RGBAFormat,
  RepeatWrapping,
  SphereGeometry,
  TubeGeometry,
  Vector3,
} from "three";
import { mergeGeometries } from "three/addons/utils/BufferGeometryUtils.js";
import type { WallMaterialLibrary, WallTextureQuality } from "../../render/materials/WallMaterialLibrary";
import { applyWallShaderTweaks } from "../../render/materials/applyWallShaderTweaks";
import { DeterministicRng } from "../../utils/Rng";
import { buildDecorativePalms } from "../buildDecorativePalms";
import type { RuntimeAnchorsSpec } from "../types";
import atmosphereJson from "./atmosphere.generated.json";
import { buildR8Market, type R8Market } from "./buildR8Market";

/**
 * R8 atmosphere overlay (docs/map-design/construction/r8-art-direction.md).
 *
 * Render-only street life generated by docs/map-design/construction/r8.py from
 * the frozen BZ-04 target: shop awnings, cross-street cables, bunting, laundry
 * and banners, wall utilities, rooftop kit and upper rooms, procedural wall-foot
 * goods and courtyard palms. It creates no colliders. The generator enforces the
 * BZ-04 clearance contract; this module only realises the records.
 */

export type Vec2 = [number, number];
export type Vec3 = [number, number, number];

type Awning = {
  id: string; center: Vec2; inward: Vec2; widthM: number; depthM: number; topZ: number; frontZ: number;
  valanceM: number; color: string; stripe: string | null; scallop: boolean;
};
type Span = { id: string; kind: "cables" | "bunting" | "laundry" | "banners"; a: Vec3; b: Vec3; sagM: number; dropM: number; seed: number };
type WallKit = {
  id: string; kind: "ac_split" | "downpipe" | "wall_cable" | "meter_box" | "wall_lamp";
  center?: Vec2; inward: Vec2; z: number; size?: Vec3; fixed?: number; horizontal?: boolean; clipsAlong?: number[];
  sagM?: number; cableTopZ?: number;
};
type Rooftop = { id: string; kind: string; pos: Vec3; alongAxis: "x" | "y"; size: Vec3; seed: number; background?: boolean };
export type R8Clutter = {
  id: string; kind: string; model: string | null; scale: number; pos: Vec3; wallPoint: Vec2; inward: Vec2;
  yawJitterDeg: number; projectionM: number;
};
type Palm = { id: string; pos: Vec3; heightM: number; yawDeg: number; widthM: number };
type Decal = { id: string; kind: "streak" | "splash"; center: Vec2; inward: Vec2; zTop: number; widthM: number; heightM: number; seed: number };

export type R8Atmosphere = {
  mapId: string;
  awnings: Awning[]; spans: Span[]; decals: Decal[]; wallKit: WallKit[]; rooftop: Rooftop[]; clutter: R8Clutter[]; palms: Palm[];
  market?: R8Market;
};

export const R8_ATMOSPHERE = atmosphereJson as unknown as R8Atmosphere;

/** Wall-pack materials whose photographs feed the R8 close-range detail layer. */
export const R8_DETAIL_MATERIAL_IDS = { plaster: "ph_worn_plaster_sun", stone: "ph_sandstone_blocks_06" } as const;

/** Wall-pack materials the R8 street-life props are dressed with. */
export const R8_PROP_MATERIAL_IDS = [
  "ph_hessian_230", "ph_rusty_metal_02", "ph_painted_metal_shutter", "ph_bz04_stone_trim_sandstone",
  "ph_brick_4_desert", "ph_bz04_weathered_brown_planks", "ph_bz04_painted_plaster_warm",
] as const;

/** The overlay is authored for one map; other maps and fixtures never receive it. */
export function r8AppliesTo(mapId: string | undefined): boolean {
  return mapId === R8_ATMOSPHERE.mapId;
}

const UP = new Vector3(0, 1, 0);

/** Design (x east, y north, z up) to world (x, y up, z north). */
export function w(x: number, y: number, z: number): Vector3 {
  return new Vector3(x, z, y);
}

/**
 * Frame for a wall-mounted item: local X along the wall, Y up, Z out of the
 * wall into the street. The design-to-world swap is a reflection, so the
 * tangent sign is chosen to keep the basis right-handed.
 */
export function wallFrame(origin: Vector3, inward: Vec2): Matrix4 {
  const n = new Vector3(inward[0], 0, inward[1]).normalize();
  const t = new Vector3().crossVectors(UP, n).normalize();
  const m = new Matrix4().makeBasis(t, UP, n);
  if (m.determinant() < 0) m.makeBasis(t.negate(), UP, n);
  return m.setPosition(origin);
}

export class Batches {
  private readonly parts = new Map<string, BufferGeometry[]>();

  add(key: string, geometry: BufferGeometry, matrix?: Matrix4): void {
    const g = geometry.index ? geometry.toNonIndexed() : geometry;
    if (g !== geometry) geometry.dispose();
    if (matrix) g.applyMatrix4(matrix);
    for (const name of Object.keys(g.attributes)) {
      if (!["position", "normal", "uv", "color"].includes(name)) g.deleteAttribute(name);
    }
    if (!g.getAttribute("uv")) {
      const count = g.getAttribute("position").count;
      g.setAttribute("uv", new Float32BufferAttribute(new Float32Array(count * 2), 2));
    }
    if (!g.getAttribute("color")) {
      const count = g.getAttribute("position").count;
      g.setAttribute("color", new Float32BufferAttribute(new Float32Array(count * 3).fill(1), 3));
    }
    let list = this.parts.get(key);
    if (!list) {
      list = [];
      this.parts.set(key, list);
    }
    list.push(g);
  }

  tinted(key: string, geometry: BufferGeometry, color: Color, matrix?: Matrix4): void {
    const g = geometry.index ? geometry.toNonIndexed() : geometry;
    const count = g.getAttribute("position").count;
    const colors = new Float32Array(count * 3);
    for (let i = 0; i < count; i += 1) {
      colors[i * 3] = color.r;
      colors[i * 3 + 1] = color.g;
      colors[i * 3 + 2] = color.b;
    }
    g.setAttribute("color", new Float32BufferAttribute(colors, 3));
    this.add(key, g, matrix);
  }

  build(root: Group, materials: Record<string, MeshStandardMaterial>, castShadow: Set<string>): void {
    for (const [key, list] of this.parts) {
      const material = materials[key];
      if (!material || list.length === 0) continue;
      const merged = mergeGeometries(list, false);
      for (const g of list) g.dispose();
      if (!merged) throw new Error(`[r8-atmosphere] failed to merge ${key}`);
      merged.computeBoundingSphere();
      const mesh = new Mesh(merged, material);
      mesh.name = `r8-${key}`;
      mesh.castShadow = castShadow.has(key);
      mesh.receiveShadow = true;
      mesh.userData.renderOnly = true;
      root.add(mesh);
    }
  }
}

export function srgb(hex: string): Color {
  return new Color(hex);
}

export function box(wd: number, h: number, d: number, x = 0, y = 0, z = 0): BufferGeometry {
  const g = new BoxGeometry(wd, h, d);
  g.translate(x, y, z);
  return g;
}

export function cylinder(radius: number, height: number, segments = 12, radiusBottom = radius): BufferGeometry {
  return new CylinderGeometry(radius, radiusBottom, height, segments, 1, false);
}

/** A cable/rope between two points hanging in a parabola-approximated catenary. */
export function catenary(a: Vector3, b: Vector3, sag: number, samples = 16): Vector3[] {
  const points: Vector3[] = [];
  for (let i = 0; i <= samples; i += 1) {
    const t = i / samples;
    const p = new Vector3().lerpVectors(a, b, t);
    p.y -= sag * 4 * t * (1 - t);
    points.push(p);
  }
  return points;
}

export function tube(points: Vector3[], radius: number, radial = 5): BufferGeometry {
  const curve = new CatmullRomCurve3(points);
  return new TubeGeometry(curve, Math.max(8, points.length * 2), radius, radial, false);
}

/** Quad strip with vertices supplied row by row (two rows). */
export function ribbon(top: Vector3[], bottom: Vector3[]): BufferGeometry {
  const positions: number[] = [];
  for (let i = 0; i < top.length - 1; i += 1) {
    const a = top[i]!, b = top[i + 1]!, c = bottom[i]!, d = bottom[i + 1]!;
    positions.push(a.x, a.y, a.z, c.x, c.y, c.z, b.x, b.y, b.z);
    positions.push(b.x, b.y, b.z, c.x, c.y, c.z, d.x, d.y, d.z);
  }
  const g = new BufferGeometry();
  g.setAttribute("position", new Float32BufferAttribute(positions, 3));
  g.computeVertexNormals();
  return g;
}

function triangle(a: Vector3, b: Vector3, c: Vector3): BufferGeometry {
  const g = new BufferGeometry();
  g.setAttribute("position", new Float32BufferAttribute([a.x, a.y, a.z, b.x, b.y, b.z, c.x, c.y, c.z], 3));
  g.computeVertexNormals();
  return g;
}

const CLOTH_COLORS = ["#b85a2c", "#c8973f", "#2f6d68", "#d9c7a0", "#35627a", "#8f3f2a", "#7a8a5a", "#e0b25a"];
const LAUNDRY_COLORS = ["#e6ddcb", "#cfc3ad", "#6f7f8f", "#b85a2c", "#3d5a74", "#d8c08a", "#9aa39a", "#efe8dc"];

function buildAwning(batches: Batches, a: Awning): void {
  const origin = w(a.center[0], a.center[1], 0);
  const frame = wallFrame(origin, a.inward);
  const base = srgb(a.color);
  const stripe = a.stripe ? srgb(a.stripe) : null;
  const half = a.widthM / 2;
  const cols = Math.max(6, Math.round(a.widthM / 0.125));
  const rows = 5;
  // Sloped cloth: from the wall head to the front bar, sagging between arms.
  const positions: number[] = [];
  const colors: number[] = [];
  const vertex = (u: number, v: number): [Vector3, Color] => {
    const x = -half + u * a.widthM;
    const z = v * a.depthM;
    const sagAcross = Math.sin(u * Math.PI) * 0.035;
    const sagDown = Math.sin(v * Math.PI) * 0.05;
    const y = a.topZ + (a.frontZ - a.topZ) * v - sagAcross * v - sagDown;
    const band = stripe && Math.floor((x + half) / 0.24) % 2 === 1;
    const c = (band ? stripe! : base).clone().multiplyScalar(0.92 + 0.08 * v);
    return [new Vector3(x, y, z), c];
  };
  for (let i = 0; i < cols; i += 1) {
    for (let j = 0; j < rows; j += 1) {
      const quad = [vertex(i / cols, j / rows), vertex(i / cols, (j + 1) / rows), vertex((i + 1) / cols, j / rows), vertex((i + 1) / cols, (j + 1) / rows)];
      for (const idx of [0, 1, 2, 2, 1, 3]) {
        const [p, c] = quad[idx]!;
        positions.push(p.x, p.y, p.z);
        colors.push(c.r, c.g, c.b);
      }
    }
  }
  const cloth = new BufferGeometry();
  cloth.setAttribute("position", new Float32BufferAttribute(positions, 3));
  cloth.setAttribute("color", new Float32BufferAttribute(colors, 3));
  cloth.computeVertexNormals();
  batches.add("cloth", cloth, frame);
  // Valance with a scalloped hem.
  const top: Vector3[] = [];
  const bottom: Vector3[] = [];
  const valCols = cols * 2;
  for (let i = 0; i <= valCols; i += 1) {
    const x = -half + (i / valCols) * a.widthM;
    const y = a.frontZ;
    const scallop = a.scallop ? Math.abs(Math.sin(((x + half) / 0.3) * Math.PI)) * 0.07 : 0;
    top.push(new Vector3(x, y, a.depthM + 0.005));
    bottom.push(new Vector3(x, y - a.valanceM + scallop, a.depthM + 0.02));
  }
  batches.tinted("cloth", ribbon(top, bottom), (stripe ?? base).clone().multiplyScalar(0.88), frame);
  // Front bar, wall ledger, short knee brackets and closed side cheeks.
  batches.add("iron", box(a.widthM + 0.04, 0.035, 0.035, 0, a.frontZ, a.depthM), frame);
  batches.add("timber", box(a.widthM + 0.08, 0.09, 0.07, 0, a.topZ + 0.03, 0.035), frame);
  for (const side of [-1, 1]) {
    const x = side * (half - 0.05);
    const from = new Vector3(x, a.topZ - 0.42, 0.02);
    const to = new Vector3(x, a.topZ - (a.topZ - a.frontZ) * 0.62, a.depthM * 0.62);
    const len = from.distanceTo(to);
    const knee = box(0.035, len, 0.035);
    const mid = new Vector3().addVectors(from, to).multiplyScalar(0.5);
    const q = new Quaternion().setFromUnitVectors(UP, new Vector3().subVectors(to, from).normalize());
    batches.add("iron", knee, new Matrix4().multiplyMatrices(frame, new Matrix4().compose(mid, q, new Vector3(1, 1, 1))));
    batches.add("iron", box(0.05, 0.12, 0.02, x, a.topZ - 0.42, 0.01), frame);
    const sx = side * half;
    batches.tinted("cloth", triangle(
      new Vector3(sx, a.topZ, 0.01),
      new Vector3(sx, a.frontZ - a.valanceM * 0.7, a.depthM),
      new Vector3(sx, a.frontZ, a.depthM),
    ), base.clone().multiplyScalar(0.8), frame);
  }
}

function buildSpan(batches: Batches, s: Span): void {
  const rng = new DeterministicRng(s.seed);
  const a = w(s.a[0], s.a[1], s.a[2]);
  const b = w(s.b[0], s.b[1], s.b[2]);
  const length = a.distanceTo(b);
  // Wall anchor plates.
  for (const p of [a, b]) batches.add("iron", box(0.08, 0.08, 0.08), new Matrix4().setPosition(p));
  if (s.kind === "cables") {
    const wires = 2 + rng.int(0, 2);
    for (let i = 0; i < wires; i += 1) {
      const dy = i * 0.06;
      const extra = rng.range(-0.08, 0.14);
      const pts = catenary(a.clone().setY(a.y - dy), b.clone().setY(b.y - dy * 0.7), s.sagM + extra, 20);
      batches.add("cable", tube(pts, 0.011));
    }
    return;
  }
  const rope = catenary(a, b, s.sagM, 24);
  batches.add("cable", tube(rope, 0.008));
  const along = new Vector3().subVectors(b, a).setY(0).normalize();
  const side = new Vector3().crossVectors(along, UP).normalize();
  const ropeAt = (t: number): Vector3 => {
    const p = new Vector3().lerpVectors(a, b, t);
    p.y -= s.sagM * 4 * t * (1 - t);
    return p;
  };
  if (s.kind === "bunting") {
    const count = Math.floor(length / 0.36);
    for (let i = 1; i < count; i += 1) {
      const t0 = (i - 0.42) / count;
      const t1 = (i + 0.42) / count;
      const p0 = ropeAt(t0);
      const p1 = ropeAt(t1);
      const tip = ropeAt(i / count).add(new Vector3(0, -s.dropM * rng.range(0.85, 1.05), 0)).addScaledVector(side, rng.range(-0.03, 0.03));
      const color = srgb(CLOTH_COLORS[rng.int(0, CLOTH_COLORS.length)]!);
      batches.tinted("cloth", triangle(p0, p1, tip), color);
    }
    return;
  }
  // Laundry garments or broad banners hanging from the line.
  const banners = s.kind === "banners";
  let t = rng.range(0.08, 0.16);
  while (t < 0.9) {
    const widthM = banners ? rng.range(0.9, 1.5) : rng.range(0.3, 0.7);
    const t1 = Math.min(0.94, t + widthM / length);
    const drop = banners ? s.dropM * rng.range(0.8, 1.0) : s.dropM * rng.range(0.55, 1.0);
    const cols = 6;
    const top: Vector3[] = [];
    const bottom: Vector3[] = [];
    for (let i = 0; i <= cols; i += 1) {
      const tt = t + (t1 - t) * (i / cols);
      const p = ropeAt(tt);
      top.push(p);
      const hem = banners ? Math.sin((i / cols) * Math.PI) * 0.06 : 0;
      bottom.push(p.clone().add(new Vector3(0, -drop + hem, 0)).addScaledVector(side, Math.sin((i / cols) * Math.PI * 2) * 0.03));
    }
    const palette = banners ? ["#c9652c", "#d98a3a", "#b85a2c", "#e0a54a", "#c07a36"] : LAUNDRY_COLORS;
    const color = srgb(palette[rng.int(0, palette.length)]!);
    batches.tinted("cloth", ribbon(top, bottom), color);
    t = t1 + (banners ? rng.range(0.04, 0.12) : rng.range(0.03, 0.1));
  }
}

function buildWallKit(batches: Batches, k: WallKit): void {
  if (k.kind === "wall_cable") {
    const clips = k.clipsAlong ?? [];
    const offset = 0.03;
    const pointAt = (along: number): Vector3 => {
      const x = k.horizontal ? along : (k.fixed ?? 0) + k.inward[0] * offset;
      const y = k.horizontal ? (k.fixed ?? 0) + k.inward[1] * offset : along;
      return w(x, y, k.z);
    };
    for (let i = 0; i < clips.length - 1; i += 1) {
      const a = pointAt(clips[i]!);
      const b = pointAt(clips[i + 1]!);
      batches.add("cable", tube(catenary(a, b, k.sagM ?? 0.06, 8), 0.009, 4));
    }
    for (const c of clips) batches.add("iron", box(0.03, 0.03, 0.03), new Matrix4().setPosition(pointAt(c)));
    return;
  }
  if (!k.center || !k.size) return;
  const frame = wallFrame(w(k.center[0], k.center[1], 0), k.inward);
  const [sx, sy, sz] = k.size;
  switch (k.kind) {
    case "ac_split": {
      const zc = k.z + sy / 2;
      const zd = sz / 2 + 0.08;
      batches.add("appliance", box(sx, sy, sz, 0, zc, zd), frame);
      batches.add("appliance", box(sx + 0.02, 0.03, sz + 0.02, 0, k.z + sy, zd), frame);
      // Front: louvred intake on the left, round fan guard on the right.
      for (let i = 0; i < 7; i += 1) {
        batches.add("grille", box(sx * 0.48, 0.018, 0.012, -sx * 0.2, k.z + 0.08 + i * (sy - 0.16) / 6, sz + 0.086), frame);
      }
      const fan = cylinder(sy * 0.36, 0.02, 18);
      fan.rotateX(Math.PI / 2);
      fan.translate(sx * 0.24, zc, sz + 0.09);
      batches.add("grille", fan, frame);
      const hub = cylinder(0.04, 0.03, 10);
      hub.rotateX(Math.PI / 2);
      hub.translate(sx * 0.24, zc, sz + 0.1);
      batches.add("appliance", hub, frame);
      // L-brackets: wall leg plus arm under the unit.
      for (const side of [-1, 1]) {
        batches.add("iron", box(0.035, 0.34, 0.035, side * sx * 0.34, k.z - 0.15, 0.02), frame);
        batches.add("iron", box(0.035, 0.035, sz + 0.1, side * sx * 0.34, k.z - 0.02, (sz + 0.1) / 2), frame);
      }
      batches.add("pipe", box(0.03, 0.55, 0.03, sx / 2 - 0.08, k.z - 0.27, 0.05), frame);
      break;
    }
    case "downpipe": {
      const pipe = cylinder(0.045, sy, 8);
      pipe.translate(0, k.z + sy / 2 + 0.12, 0.08);
      batches.add("pipe", pipe, frame);
      for (let y = k.z + 1.2; y < k.z + sy; y += 1.9) batches.add("iron", box(0.12, 0.03, 0.1, 0, y, 0.05), frame);
      const shoe = cylinder(0.045, 0.22, 8);
      shoe.rotateX(Math.PI / 4);
      shoe.translate(0, k.z + 0.1, 0.14);
      batches.add("pipe", shoe, frame);
      break;
    }
    case "meter_box": {
      batches.add("metalBox", box(sx, sy, sz, 0, k.z + sy / 2, sz / 2), frame);
      batches.add("grille", box(0.008, sy * 0.9, 0.006, sx * 0.1, k.z + sy / 2, sz + 0.003), frame);
      batches.add("panel", box(sx * 0.32, sy * 0.18, 0.008, -sx * 0.18, k.z + sy * 0.7, sz + 0.004), frame);
      batches.add("iron", box(0.02, 0.05, 0.02, sx * 0.3, k.z + sy / 2, sz + 0.01), frame);
      const top = (k.cableTopZ ?? k.z + 1.5) - (k.z + sy);
      if (top > 0.05) batches.add("cable", box(0.02, top, 0.02, 0.06, k.z + sy + top / 2, 0.03), frame);
      break;
    }
    case "wall_lamp": {
      batches.add("iron", box(0.03, 0.03, 0.36, 0, k.z + 0.34, 0.18), frame);
      batches.add("iron", box(0.02, 0.3, 0.02, 0, k.z + 0.2, 0.02), frame);
      batches.add("iron", box(0.16, 0.03, 0.16, 0, k.z + 0.3, 0.36), frame);
      batches.add("lamp", box(0.12, 0.2, 0.12, 0, k.z + 0.18, 0.36), frame);
      break;
    }
  }
}

function roofFrame(r: Rooftop, yawJitter: number): Matrix4 {
  const yaw = (r.alongAxis === "y" ? Math.PI / 2 : 0) + yawJitter;
  return new Matrix4().compose(w(r.pos[0], r.pos[1], r.pos[2]), new Quaternion().setFromAxisAngle(UP, yaw), new Vector3(1, 1, 1));
}

function buildRooftop(batches: Batches, r: Rooftop): void {
  const rng = new DeterministicRng(r.seed);
  const [sx, sd, sh] = r.size;
  const jitter = r.kind === "roof_room" ? 0 : rng.range(-0.12, 0.12);
  const frame = roofFrame(r, jitter);
  switch (r.kind) {
    case "roof_room": {
      batches.add("roomPlaster", box(sx, sh, sd, 0, sh / 2, 0), frame);
      batches.add("roomTrim", box(sx + 0.1, 0.1, sd + 0.1, 0, sh + 0.05, 0), frame);
      // Plank door in a stone frame, and a small shuttered window.
      const face = rng.next() < 0.5 ? 1 : -1;
      const dx = rng.range(-sx / 2 + 0.6, sx / 2 - 0.6);
      const fz = face * (sd / 2);
      batches.add("roomTrim", box(0.98, 2.1, 0.08, dx, 1.05, fz + face * 0.02), frame);
      batches.add("void", box(0.8, 1.95, 0.1, dx, 0.98, fz + face * 0.035), frame);
      batches.add("iron", box(0.02, 0.02, 0.04, dx + 0.3, 1.0, fz + face * 0.1), frame);
      const wx = rng.range(-sx / 2 + 0.5, sx / 2 - 0.5);
      batches.add("roomTrim", box(0.7, 0.72, 0.08, wx, sh - 0.9, -fz - face * 0.02), frame);
      batches.add("grille", box(0.52, 0.56, 0.1, wx, sh - 0.9, -fz - face * 0.03), frame);
      for (const side of [-1, 1]) batches.add("void", box(0.27, 0.6, 0.03, wx + side * 0.42, sh - 0.9, -fz - face * 0.07), frame);
      if (rng.next() < 0.5) {
        batches.add("timber", box(0.9, 0.04, 0.35, 0, 2.15, face * (sd / 2 + 0.17)), frame);
      }
      break;
    }
    case "ac_condenser": {
      batches.add("appliance", box(sx, sh * 0.85, sd, 0, sh * 0.85 / 2 + 0.1, 0), frame);
      const fan = cylinder(sd * 0.36, 0.02, 16);
      fan.translate(0, sh * 0.85 + 0.11, 0);
      batches.add("grille", fan, frame);
      batches.add("iron", box(sx * 0.9, 0.1, 0.06, 0, 0.05, sd * 0.35), frame);
      batches.add("iron", box(sx * 0.9, 0.1, 0.06, 0, 0.05, -sd * 0.35), frame);
      break;
    }
    case "water_tank": {
      const stand = 0.45;
      const colors = ["#2b2926", "#2b2926", "#8a9ea3", "#cdbb95", "#3c5566"];
      const color = srgb(colors[rng.int(0, colors.length)]!);
      const tank = cylinder(sx / 2, sh, 16);
      tank.translate(0, stand + sh / 2, 0);
      batches.tinted("tank", tank, color, frame);
      const lid = cylinder(sx * 0.2, 0.1, 12);
      lid.translate(0, stand + sh + 0.05, 0);
      batches.tinted("tank", lid, color, frame);
      for (const t of [0.25, 0.5, 0.75]) {
        const band = cylinder(sx / 2 + 0.012, 0.035, 16);
        band.translate(0, stand + sh * t, 0);
        batches.tinted("tank", band, color.clone().multiplyScalar(0.85), frame);
      }
      for (const [x, z] of [[-1, -1], [1, -1], [-1, 1], [1, 1]] as const) {
        batches.add("iron", box(0.05, stand, 0.05, x * sx * 0.38, stand / 2, z * sx * 0.38), frame);
      }
      batches.add("iron", box(sx * 0.85, 0.05, sx * 0.85, 0, stand, 0), frame);
      break;
    }
    case "solar_heater": {
      const panel = box(sx, 0.05, 1.5);
      panel.rotateX(-0.6);
      panel.translate(0, 0.62, 0.05);
      batches.add("panel", panel, frame);
      const cyl = cylinder(0.2, sx + 0.1, 12);
      cyl.rotateZ(Math.PI / 2);
      cyl.translate(0, 1.18, -0.62);
      batches.add("appliance", cyl, frame);
      for (const x of [-sx / 2 + 0.05, sx / 2 - 0.05]) {
        batches.add("iron", box(0.04, 1.1, 0.04, x, 0.55, -0.62), frame);
        batches.add("iron", box(0.04, 0.12, 0.04, x, 0.06, 0.62), frame);
      }
      break;
    }
    case "dish": {
      batches.add("iron", box(0.05, sh * 0.7, 0.05, 0, sh * 0.35, 0), frame);
      const dish = new SphereGeometry(sx / 2, 14, 6, 0, Math.PI * 2, 0, 0.9);
      dish.scale(1, 0.4, 1);
      dish.rotateX(-1.2);
      dish.translate(0, sh * 0.72, 0.08);
      batches.add("dish", dish, frame);
      batches.add("iron", box(0.02, 0.02, 0.4, 0, sh * 0.8, 0.28), frame);
      break;
    }
    case "antenna": {
      batches.add("iron", box(0.035, sh, 0.035, 0, sh / 2, 0), frame);
      for (let i = 0; i < 4; i += 1) {
        const len = 0.9 - i * 0.14;
        batches.add("iron", box(len, 0.018, 0.018, 0, sh - 0.25 - i * 0.2, 0), frame);
      }
      batches.add("iron", box(0.018, 0.018, 0.7, 0, sh - 0.55, 0), frame);
      break;
    }
    case "rebar": {
      batches.add("concrete", box(0.3, 0.35, 0.3, 0, 0.175, 0), frame);
      for (const [x, z] of [[-1, -1], [1, -1], [-1, 1], [1, 1]] as const) {
        const rod = cylinder(0.009, sh, 5);
        rod.rotateZ(x * rng.range(0.02, 0.12));
        rod.rotateX(z * rng.range(0.02, 0.12));
        rod.translate(x * 0.09, 0.35 + sh / 2, z * 0.09);
        batches.add("rust", rod, frame);
      }
      break;
    }
    case "drum": {
      const drum = cylinder(sx / 2, sh, 14);
      drum.translate(0, sh / 2, 0);
      batches.tinted("tank", drum, srgb(rng.next() < 0.5 ? "#5e3a24" : "#3c5566"), frame);
      break;
    }
  }
}

/** Procedural wall-foot goods that have no registered model. */
function buildClutterProcedural(batches: Batches, c: R8Clutter): void {
  const frame = wallFrame(w(c.wallPoint[0], c.wallPoint[1], c.pos[2]), c.inward);
  const rng = new DeterministicRng(c.id.length * 7919 + Math.round(c.pos[0] * 131 + c.pos[1] * 17));
  if (c.kind === "gas") {
    const paint = srgb(["#56687a", "#7d4331", "#6b6f56", "#8a7a4e"][rng.int(0, 4)]!);
    const body = cylinder(0.13, 0.5, 16);
    body.translate(0, 0.33, 0.15);
    batches.tinted("tank", body, paint, frame);
    const shoulder = new SphereGeometry(0.13, 16, 6, 0, Math.PI * 2, 0, Math.PI / 2);
    shoulder.translate(0, 0.58, 0.15);
    batches.tinted("tank", shoulder, paint, frame);
    const foot = cylinder(0.12, 0.08, 16);
    foot.translate(0, 0.04, 0.15);
    batches.tinted("tank", foot, paint.clone().multiplyScalar(0.7), frame);
    const collar = cylinder(0.075, 0.1, 12);
    collar.translate(0, 0.74, 0.15);
    batches.add("iron", collar, frame);
    const valve = cylinder(0.025, 0.06, 8);
    valve.translate(0, 0.7, 0.15);
    batches.add("pipe", valve, frame);
  } else if (c.kind === "bricks") {
    for (let layer = 0; layer < 4; layer += 1) {
      for (let i = 0; i < 3; i += 1) {
        batches.tinted("brick", box(0.15, 0.065, 0.23, -0.16 + i * 0.16 + (layer % 2) * 0.03, 0.035 + layer * 0.07, 0.14),
          new Color(0.55, 0.36, 0.24).multiplyScalar(rng.range(0.8, 1.1)), frame);
      }
    }
  }
}

const DECAL_VARIANTS = 4;

/**
 * Procedural stain atlas (4 variants side by side, alpha in every channel):
 * streaks are ragged vertical runs that thin and fade downward; splashes are
 * damp blooms that are darkest at the foot of the wall.
 */
function createStainAtlas(kind: Decal["kind"], seed: number): DataTexture {
  const w = 64 * DECAL_VARIANTS;
  const h = 128;
  const data = new Uint8Array(w * h * 4);
  const rng = new DeterministicRng(seed);
  for (let v = 0; v < DECAL_VARIANTS; v += 1) {
    const lanes = Array.from({ length: 64 }, (_, x) => {
      const centre = Math.abs(x - 31.5) / 32;
      return { length: kind === "streak" ? rng.range(0.25, 1) * (1 - centre * 0.6) : 1, weight: rng.range(0.5, 1) };
    });
    for (let y = 0; y < h; y += 1) {
      const t = y / (h - 1); // 0 = top of decal
      for (let x = 0; x < 64; x += 1) {
        const lane = lanes[x]!;
        const edge = 1 - Math.min(1, Math.abs(x - 31.5) / 31.5);
        let a: number;
        if (kind === "streak") {
          const run = t < lane.length ? (1 - t / lane.length) : 0;
          a = Math.pow(run, 0.7) * lane.weight * Math.pow(edge, 0.35) * (0.75 + 0.25 * rng.next());
        } else {
          const bloom = Math.pow(t, 1.6) * Math.pow(edge, 0.6);
          a = bloom * (0.7 + 0.3 * rng.next());
        }
        const i = (y * w + v * 64 + x) * 4;
        const value = Math.round(Math.max(0, Math.min(1, a)) * 255);
        data[i] = value; data[i + 1] = value; data[i + 2] = value; data[i + 3] = value;
      }
    }
  }
  const texture = new DataTexture(data, w, h, RGBAFormat);
  texture.wrapS = RepeatWrapping;
  texture.flipY = true;
  texture.needsUpdate = true;
  return texture;
}

function buildDecal(batches: Batches, d: Decal): void {
  const origin = w(d.center[0], d.center[1], 0);
  const frame = wallFrame(origin, d.inward);
  const plane = new PlaneGeometry(d.widthM, d.heightM);
  plane.translate(0, d.zTop - d.heightM / 2, d.kind === "splash" ? 0.014 : 0.012);
  const variant = d.seed % DECAL_VARIANTS;
  const uv = plane.getAttribute("uv");
  for (let i = 0; i < uv.count; i += 1) uv.setX(i, (variant + uv.getX(i)) / DECAL_VARIANTS);
  batches.add(d.kind === "streak" ? "stainStreak" : "stainSplash", plane, frame);
}

export type R8MaterialFactory = ReturnType<typeof r8MaterialFactory>;

/** Plain and pack-photographed material constructors shared by the R8 builders. */
export function r8MaterialFactory(wallMaterials: WallMaterialLibrary | null, quality: WallTextureQuality, floorTopY: number) {
  const std = (name: string, color: string, roughness: number, metalness = 0, extra: Partial<MeshStandardMaterial> = {}): MeshStandardMaterial => {
    const m = new MeshStandardMaterial({ color: srgb(color), roughness, metalness, vertexColors: true });
    Object.assign(m, extra);
    m.name = name;
    return m;
  };
  // Pack materials give every prop a photographed surface at a consistent
  // world texel density; vertex colour still tints (awning dyes, tank paint).
  // `gain` renormalises a photographed albedo whose mean is well below white,
  // so vertex dyes keep their authored value instead of multiplying to near-black.
  const packed = (id: string, name: string, fallback: string, opts: { tint?: string; gain?: number; tileScale?: number; roughness?: number; metalness?: number; side?: typeof DoubleSide } = {}): MeshStandardMaterial => {
    if (!wallMaterials || !wallMaterials.getMaterialIds().includes(id)) {
      return std(name, fallback, opts.roughness ?? 0.9, opts.metalness ?? 0, opts.side ? { side: opts.side } : {});
    }
    const m = wallMaterials.createStandardMaterial(id, quality);
    m.name = name;
    m.vertexColors = true;
    if (opts.tint) m.color.set(opts.tint);
    if (opts.gain) m.color.multiplyScalar(opts.gain);
    if (opts.roughness !== undefined) m.roughness = opts.roughness;
    if (opts.metalness !== undefined) m.metalness = opts.metalness;
    if (opts.side !== undefined) m.side = opts.side;
    applyWallShaderTweaks(m, { albedoBoost: 1, tileSizeM: wallMaterials.getTileSizeM(id) * (opts.tileScale ?? 1), floorTopY });
    return m;
  };
  return { std, packed };
}

function materialSet(wallMaterials: WallMaterialLibrary | null, quality: WallTextureQuality, floorTopY: number): Record<string, MeshStandardMaterial> {
  const { std, packed } = r8MaterialFactory(wallMaterials, quality, floorTopY);
  return {
    cloth: packed("ph_hessian_230", "r8_awning_cloth", "#ffffff", { tint: "#ffffff", gain: 2.4, tileScale: 2.2, side: DoubleSide }),
    iron: packed("ph_rusty_metal_02", "r8_dark_iron", "#2e2924", { tint: "#6d6258", tileScale: 0.35, roughness: 0.75, metalness: 0.4 }),
    cable: std("r8_cable_iron", "#1c1916", 0.8, 0.1),
    appliance: packed("ph_painted_metal_shutter", "r8_appliance_metal", "#b3a88f", { tint: "#d6ccb4", tileScale: 0.4, roughness: 0.62 }),
    metalBox: packed("ph_painted_metal_shutter", "r8_meter_metal", "#8e8a80", { tint: "#9c978c", tileScale: 0.3, roughness: 0.6 }),
    grille: std("r8_grille_metal", "#3a3733", 0.7, 0.3),
    pipe: packed("ph_rusty_metal_02", "r8_pipe_metal", "#8b857a", { tint: "#a39a8c", tileScale: 0.5, roughness: 0.6, metalness: 0.35 }),
    lamp: std("r8_lamp_glass", "#f1c27a", 0.4, 0, { emissive: srgb("#a86a24"), emissiveIntensity: 0.25 }),
    tank: packed("ph_painted_metal_shutter", "r8_tank_metal", "#ffffff", { tint: "#ffffff", gain: 2.0, tileScale: 0.6, roughness: 0.55 }),
    panel: std("r8_panel_glass", "#243446", 0.25, 0.3),
    dish: std("r8_dish_metal", "#d9d4ca", 0.5, 0.2, { side: DoubleSide }),
    concrete: packed("ph_bz04_stone_trim_sandstone", "r8_rooftop_stone", "#9a8a74"),
    rust: std("r8_rebar_metal", "#6a3d24", 0.8, 0.4),
    brick: packed("ph_brick_4_desert", "r8_stack_brick", "#ffffff", { tint: "#ffffff", gain: 1.6 }),
    void: packed("ph_bz04_weathered_brown_planks", "r8_door_timber", "#4a3526", { tint: "#8a6a4e", tileScale: 0.6 }),
    timber: packed("ph_bz04_weathered_brown_planks", "r8_hood_timber", "#6b4f36", { tint: "#9a7a5c", tileScale: 0.6 }),
    roomPlaster: packed("ph_bz04_painted_plaster_warm", "r8_room_plaster", "#d8c29a"),
    roomTrim: packed("ph_bz04_stone_trim_sandstone", "r8_room_stone_trim", "#c9b08a"),
    stainStreak: std("r8_stain_decal", "#3a2a1c", 1, 0, {
      transparent: true, opacity: 0.58, depthWrite: false, alphaMap: createStainAtlas("streak", 11), vertexColors: false,
      polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -2,
    }),
    stainSplash: std("r8_stain_decal", "#4a3726", 1, 0, {
      transparent: true, opacity: 0.5, depthWrite: false, alphaMap: createStainAtlas("splash", 23), vertexColors: false,
      polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -2,
    }),
  };
}

export type BuildR8AtmosphereOptions = {
  seed: number;
  wallMaterials: WallMaterialLibrary | null;
  wallQuality: WallTextureQuality;
  palmQuality: WallTextureQuality;
  floorTopY: number;
  data?: R8Atmosphere;
};

export function buildR8Atmosphere(options: BuildR8AtmosphereOptions): Group {
  const data = options.data ?? R8_ATMOSPHERE;
  const root = new Group();
  root.name = "r8-atmosphere";
  const batches = new Batches();
  for (const a of data.awnings) buildAwning(batches, a);
  for (const s of data.spans) buildSpan(batches, s);
  for (const k of data.wallKit) buildWallKit(batches, k);
  for (const d of data.decals ?? []) buildDecal(batches, d);
  for (const r of data.rooftop) buildRooftop(batches, r);
  for (const c of data.clutter) if (!c.model) buildClutterProcedural(batches, c);
  const materials = materialSet(options.wallMaterials, options.wallQuality, options.floorTopY);
  batches.build(root, materials, new Set(["cloth", "appliance", "metalBox", "tank", "roomPlaster", "roomTrim", "panel", "dish", "iron", "brick", "concrete", "timber", "void"]));

  if (data.market) {
    root.add(buildR8Market(data.market, r8MaterialFactory(options.wallMaterials, options.wallQuality, options.floorTopY)));
  }

  if (data.palms.length > 0) {
    const anchors: RuntimeAnchorsSpec = {
      mapId: "bazaar-map",
      anchors: data.palms.map((p) => ({
        id: p.id,
        type: "decorative_palm",
        zone: "R8_ENCLOSED_GARDEN",
        pos: { x: p.pos[0], y: p.pos[1], z: p.pos[2] },
        yawDeg: p.yawDeg,
        widthM: p.widthM,
        heightM: p.heightM,
      })),
    };
    const palms = buildDecorativePalms(anchors, options.seed, options.palmQuality);
    if (palms) root.add(palms);
  }
  root.userData.r8Counts = {
    awnings: data.awnings.length, spans: data.spans.length, wallKit: data.wallKit.length,
    rooftop: data.rooftop.length, clutterProcedural: data.clutter.filter((c) => !c.model).length, palms: data.palms.length,
    marketWallArt: data.market?.wallArt.length ?? 0, marketLanterns: data.market?.lanterns.length ?? 0, marketGoods: data.market?.counterGoods.length ?? 0,
  };
  return root;
}
